---

name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_ubuntu:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: actions/cache@v2
        with:
          path: ~/.cache/
          key: ${{ matrix.os }}
      - name: setup tox
        run: |
          python --version
          python -m pip install --upgrade pip
          python -m pip install --upgrade 'tox<4'
      - name: run ${{ matrix.tox.env }}
        run: |
          tox
